# username and password for server encrypted in local txt-file
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 192.168.1.236
  username: <%= File.read('/Users/danielkasper/credentials.txt').split("\n").detect{|line| line.start_with?('username:')}.split(':')[1].strip %>
  password: <%= File.read('/Users/danielkasper/credentials.txt').split("\n").detect{|line| line.start_with?('password:')}.split(':')[1].strip %>

development:
  <<: *default
  database: mydatabase

test:
  <<: *default
  database: mydatabase_test

production:
  <<: *default
  database: mydatabase_production

