# username and password for server encrypted in local txt-file
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= File.read('/Users/danielkasper/credentials.txt').split("\n").detect{|line| line.start_with?('host:')}.split(':')[1].strip %>
  username: <%= File.read('/Users/danielkasper/credentials.txt').split("\n").detect{|line| line.start_with?('username:')}.split(':')[1].strip %>
  password: '#Martinogsusanne18'

development:
  <<: *default
  database: postgres 

test:
  <<: *default
  database: postgres_test

production:
  <<: *default
  database: postgres_production

